# Generated by Django 4.0.2 on 2022-02-20 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20220220_0101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='organization',
        ),
    ]
