# Generated by Django 3.2.5 on 2022-02-22 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_report_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='report_contact',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
